name: Update specific repo

on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo to use
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - uses: morten-olsen/git-law@main
        with:
          include: morten-olsen/*
